codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        # basic
        target: auto
        threshold: 5%
        base: auto
      types:
        flags:
          - Types
        target: auto
        threshold: 5%
        base: auto
      client-ng:
        flags:
          - ClientNg
        target: auto
        threshold: 5%
        base: auto
      db-core:
        flags:
          - DbCore
        target: auto
        threshold: 5%
        base: auto
      api-route-image:
        flags:
          - ApiRouteImage
        target: auto
        threshold: 5%
        base: auto
parsers:
  javascript:
    enable_partials: yes
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: no

flags:
  ClientNg:
    paths:
      - packages/client-ng/src
  Types:
    paths:
      - packages/types/src
  DbCore:
    paths:
      - packages/db-core/src
  ApiRouteImage:
    paths:
      - packages/api-route-image/src
