name: Publish Packages
on:
  release:
    types: [published]

jobs:
  release_npm:
    runs-on: ubuntu-latest
    name: Publish Package to NPM
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install Packages
        run: |
          npm ci
          npx lerna bootstrap --ci
      - name: Build Package
        run: npm run build
      - name: Prepare Package
        run: |
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Upload Package
        run: npx lerna publish from-git --yes
